export const metadata = {
  title: 'Configurateur Emersya',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  )
}
